# Generated by Django 3.2.4 on 2021-06-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ['title'], 'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='tests',
            name='slug',
        ),
    ]
