# Generated by Django 3.2.4 on 2021-06-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-time_create'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='tests',
            name='formula',
            field=models.CharField(max_length=255, verbose_name='Формула'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='indicators',
            field=models.TextField(blank=True, verbose_name='Показатели к тестированию'),
        ),
    ]
