# Generated by Django 3.2.4 on 2021-06-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210603_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tests',
            options={'ordering': ['pk'], 'verbose_name': 'Тесты', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AddField(
            model_name='tests',
            name='indicators',
            field=models.CharField(default='', max_length=255, verbose_name='Показатели к тестированию'),
        ),
    ]
