# Generated by Django 3.2.4 on 2021-06-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210604_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
