# Generated by Django 3.2.4 on 2021-06-06 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_tests_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
