# Generated by Django 3.2.4 on 2021-06-06 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_tests_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='formula',
            field=models.CharField(default=django.utils.timezone.now, max_length=55, verbose_name='Формула'),
            preserve_default=False,
        ),
    ]
