# Generated by Django 3.2.4 on 2021-06-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_tests_formula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='formula',
            field=models.CharField(max_length=120, verbose_name='Формула'),
        ),
    ]
